<a href="https://colab.research.google.com/github/anujphadke/Impala/blob/impala5582-4/tensorflow_basic_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
x = tf.ones((2,2))
print(x.shape)
print(x.dtype)
print(x)

(2, 2)
<dtype: 'float32'>
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [5]:
x = tf.random.normal((5,1), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-1.2140051 ]
 [-0.30801517]
 [ 0.17277092]
 [-0.54932845]
 [ 0.9166983 ]], shape=(5, 1), dtype=float32)


In [11]:
y = tf.random.uniform((5,1), minval=0, maxval=5)
print(y)

tf.Tensor(
[[3.944313 ]
 [0.5231744]
 [1.8737048]
 [1.6271019]
 [4.685378 ]], shape=(5, 1), dtype=float32)


In [14]:
a=tf.Variable(initial_value=tf.random.normal((3,1)))
print(a)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.53434163],
       [ 0.22541595],
       [-1.3331264 ]], dtype=float32)>


In [15]:
a.assign(tf.ones((3,1)))
print(a)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


In [18]:
m=tf.ones((3,1))
n=tf.square(m) + 5
o=tf.sqrt(n)
print(m)
print(n)
print(o)

tf.Tensor(
[[1.]
 [1.]
 [1.]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[6.]
 [6.]
 [6.]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[2.4494896]
 [2.4494896]
 [2.4494896]], shape=(3, 1), dtype=float32)
